<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use DB;
class ServiciosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('servicios')->insert([ 'nombre' => 'Alisado AGI ONE', 'precio' => 2, 'duracion' => '01:30:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'ALISADO KER EMPLEADO**no disponible con descuento*', 'precio' => 1, 'duracion' => '04:00:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'ALISADO KERATINA', 'precio' => 1, 'duracion' => '03:00:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'anti-hair loss et nature', 'precio' => 5, 'duracion' => '00:10:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'Arreglo barba', 'precio' => 5, 'duracion' => '00:15:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'Arreglo uña gel', 'precio' => 3.5, 'duracion' => '00:10:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'Arreglo uña semipermanentes', 'precio' => 2.5, 'duracion' => '00:10:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'bbglow', 'precio' => 80, 'duracion' => '00:30:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'BONO 6 MASAJES 25 MINUTOS', 'precio' => 75, 'duracion' => '00:25:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'BONO 6 MASAJES 50 MINUTOS', 'precio' => 125, 'duracion' => '00:50:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'BONO PRESOTERAPIA 5 + 1 (30 MINUTOS)', 'precio' => 49.9, 'duracion' => '00:30:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'BONO PRESOTERAPIA 5 + 2 (45 MINUTOS)', 'precio' => 95.9, 'duracion' => '00:45:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'BONO RADIOFRECUENCIA FACIAL', 'precio' => 150, 'duracion' => '00:50:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'BONO RADIOFRECUENCIA/CAVITACIÓN CORPORAL', 'precio' => 200, 'duracion' => '00:50:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'BOTOX CAPILAR', 'precio' => 30, 'duracion' => '00:30:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'BOTOX EMPLEADO', 'precio' => 10, 'duracion' => '00:20:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'CEJAS PINZA', 'precio' => 4, 'duracion' => '00:00:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'CELULAS MADRE EMPLEADOS', 'precio' => 3, 'duracion' => '00:20:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'Células madre et nature', 'precio' => 5, 'duracion' => '00:10:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'CERA ABDOMEN', 'precio' => 15, 'duracion' => '00:20:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'CERA AXILA', 'precio' => 7, 'duracion' => '00:20:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'CERA BRAZO', 'precio' => 14, 'duracion' => '00:20:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'CERA EMPLEADO AXILA/INGLES', 'precio' => 3, 'duracion' => '00:15:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'CERA EMPLEADO MEDIA PIERNA', 'precio' => 3, 'duracion' => '00:15:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'CERA EMPLEADO PIERNA COMPLETA', 'precio' => 10, 'duracion' => '00:15:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'CERA ESPALDA', 'precio' => 15, 'duracion' => '00:20:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'CERA INGLE BRASILEÑA', 'precio' => 10, 'duracion' => '00:10:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'CERA INGLES NORMAL', 'precio' => 7, 'duracion' => '00:20:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'CERA LABIO', 'precio' => 3, 'duracion' => '00:00:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'CERA MEDIA PIERNA', 'precio' => 14, 'duracion' => '00:20:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'CERA MENTON', 'precio' => 3, 'duracion' => '00:10:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'CERA NARIZ/CEJAS', 'precio' => 3, 'duracion' => '00:00:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'CERA PATILLA', 'precio' => 3, 'duracion' => '00:10:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'CERA PECHO', 'precio' => 15, 'duracion' => '00:20:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'CERA PERIANAL', 'precio' => 5, 'duracion' => '00:20:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'CERA PIERNA COMPLETA', 'precio' => 20, 'duracion' => '00:20:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'CERA PUBIS COMPLETO', 'precio' => 15, 'duracion' => '00:20:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'Champú tratamiento', 'precio' => 3, 'duracion' => '00:00:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'COLOCACION PESTAÑAS POSTIZAS EVENTOS', 'precio' => 10, 'duracion' => '00:10:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'COLOR FANTASÍA 45GR', 'precio' => 12, 'duracion' => '00:40:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'CORTE FLEQUILLO', 'precio' => 4, 'duracion' => '00:15:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'CORTE HOMBRE', 'precio' => 6, 'duracion' => '00:20:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'corte hombre degradado', 'precio' => 10, 'duracion' => '00:30:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'CORTE MUJER', 'precio' => 6, 'duracion' => '00:20:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'CORTE NIÑO/A', 'precio' => 4, 'duracion' => '00:15:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'Corte/peinado empleado', 'precio' => 0, 'duracion' => '00:30:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'curso automaquillaje', 'precio' => 30, 'duracion' => '01:00:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'DEPILACION BARBILLA HILO', 'precio' => 6, 'duracion' => '00:10:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'DEPILACIÓN CEJAS HILO', 'precio' => 7, 'duracion' => '00:10:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'DEPILACION FACIAL COMPLETA HILO', 'precio' => 30, 'duracion' => '00:30:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'DEPILACION LABIO HILO', 'precio' => 6, 'duracion' => '00:10:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'DEPILACIÓN MENTON HILO', 'precio' => 6, 'duracion' => '00:10:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'DEPILACION PATILLAS HILO', 'precio' => 6, 'duracion' => '00:10:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'DERMAPEN', 'precio' => 100, 'duracion' => '01:00:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'Energic et nature', 'precio' => 4, 'duracion' => '00:10:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'ESMALTADO PERMANENTE EMPLEADO MANOS/PIES', 'precio' => 5, 'duracion' => '00:20:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'ESMALTADO PERMANENTE PIES', 'precio' => 18, 'duracion' => '00:30:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'esmaltado permanente sin manicura', 'precio' => 12, 'duracion' => '00:10:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'ESMALTADO TRADICIONAL PIES', 'precio' => 12, 'duracion' => '00:15:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'esmaltar uñas tradicional', 'precio' => 4, 'duracion' => '00:00:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'extension fantasía', 'precio' => 3.5, 'duracion' => '00:15:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'EXTENSIONES 20 TIRAS 40 CM', 'precio' => 110, 'duracion' => '00:50:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'EXTENSIONES 20 TIRAS 50 CMS', 'precio' => 130, 'duracion' => '00:50:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'EXTENSIONES 20 TIRAS 55 CMS', 'precio' => 140, 'duracion' => '00:50:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'EXTENSIONES 20 TIRAS 60 CMS', 'precio' => 150, 'duracion' => '00:50:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'EXTENSIONES 20 TIRAS 65 CMS', 'precio' => 160, 'duracion' => '00:50:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'EXTENSIONES 40 TIRAS 50 CMS', 'precio' => 195, 'duracion' => '00:50:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'EXTENSIONES CORTINA 100 GRAMOS 30 CMS', 'precio' => 130, 'duracion' => '00:50:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'EXTENSIONES CORTINA 100 GRAMOS 35 CMS', 'precio' => 140, 'duracion' => '00:50:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'EXTENSIONES CORTINA 100 GRAMOS 50 CMS', 'precio' => 150, 'duracion' => '00:50:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'EXTENSIONES CORTINA 100 GRAMOS 65 CMS', 'precio' => 160, 'duracion' => '00:50:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'EXTENSIONES DE PESTAÑAS', 'precio' => 50, 'duracion' => '01:00:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'EXTENSIONES PESTAÑAS EMPLEADO', 'precio' => 10, 'duracion' => '00:30:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'EXTRA', 'precio' => 2, 'duracion' => '00:15:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'hialuron pen AH', 'precio' => 250, 'duracion' => '01:00:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'hialuron pen bono 10 sesiones', 'precio' => 400, 'duracion' => '01:00:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'hialuron pen sesion mesoterapia', 'precio' => 50, 'duracion' => '01:00:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'Hidratación tsubaki', 'precio' => 45, 'duracion' => '00:30:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'HIDRATACION WOW', 'precio' => 19, 'duracion' => '00:40:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'HIGIENE FACIAL', 'precio' => 30, 'duracion' => '01:00:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'KERATINA EMPLEADO', 'precio' => 3, 'duracion' => '00:20:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'keratina pestañas', 'precio' => 40, 'duracion' => '01:00:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'LASER ABDOMEN HOMBRE', 'precio' => 20, 'duracion' => '00:20:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'LASER ANTEBRAZOS', 'precio' => 15, 'duracion' => '00:19:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'LASER AXILA', 'precio' => 5, 'duracion' => '00:15:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'LASER BRAZOS ENTEROS', 'precio' => 29, 'duracion' => '00:29:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'LASER DEDOS MANOS O PIES', 'precio' => 10, 'duracion' => '00:19:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'LASER EMPEINE', 'precio' => 10, 'duracion' => '00:18:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'LASER ESPALDA', 'precio' => 25, 'duracion' => '00:20:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'LASER GLUTEOS', 'precio' => 20, 'duracion' => '00:20:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'LASER INGLES', 'precio' => 10, 'duracion' => '00:19:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'LASER INGLES BRASILEÑAS', 'precio' => 20, 'duracion' => '00:19:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'LASER LINEA ALBA', 'precio' => 10, 'duracion' => '00:19:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'LASER LUMBARES', 'precio' => 15, 'duracion' => '00:20:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'LASER MANOS', 'precio' => 10, 'duracion' => '00:19:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'LASER MEDIA PIERNA', 'precio' => 20, 'duracion' => '00:20:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'LASER MEDIOS BRAZOS', 'precio' => 15, 'duracion' => '00:19:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'LASER MENTON', 'precio' => 10, 'duracion' => '00:19:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'LASER MUSLOS', 'precio' => 20, 'duracion' => '00:20:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'LASER PASTILLAS', 'precio' => 10, 'duracion' => '00:19:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'LASER PECHO HOMBRE', 'precio' => 20, 'duracion' => '00:20:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'LASER PERIANAL', 'precio' => 5, 'duracion' => '00:15:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'LASER PIERNAS ENTERAS', 'precio' => 39, 'duracion' => '00:39:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'LASER PUBIS COMPLETO', 'precio' => 30, 'duracion' => '00:30:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'lifting y tinte de pestañas', 'precio' => 30, 'duracion' => '01:00:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'LIMMPIEZA FACIAL', 'precio' => 30, 'duracion' => '00:30:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'MAKE UP GEMA GUZMAN', 'precio' => 35, 'duracion' => '00:59:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'manicura con esmaltado permanente', 'precio' => 18, 'duracion' => '00:25:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'manicura con esmaltado tradicional', 'precio' => 8, 'duracion' => '00:15:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'MANICURA TRADICIONAL', 'precio' => 8, 'duracion' => '00:15:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'MAQUILLAJE EVENTO', 'precio' => 25, 'duracion' => '00:30:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'MASAJE 25 MINUTOS', 'precio' => 15, 'duracion' => '00:25:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'MASAJE 50 MINUTOS', 'precio' => 25, 'duracion' => '00:50:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'Mascara de pestañas semipermanente', 'precio' => 30, 'duracion' => '00:20:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'MASCARILLA COLAGENO FACIAL', 'precio' => 10, 'duracion' => '00:15:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'matiz cabello corto', 'precio' => 5, 'duracion' => '00:00:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'matiz cabello extra largo', 'precio' => 7, 'duracion' => '00:10:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'matiz cabello largo', 'precio' => 6, 'duracion' => '00:10:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'matiz cabello XXL', 'precio' => 8, 'duracion' => '00:10:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'MATIZ EMPLEADO', 'precio' => 2, 'duracion' => '00:10:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'Matiz sin amoníaco cabello corto', 'precio' => 7, 'duracion' => '00:00:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'matiz sin amoniaco cabello extra largo', 'precio' => 10, 'duracion' => '00:10:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'matiz sin amoniaco cabello largo', 'precio' => 8, 'duracion' => '00:10:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'matiz sin amoniaco cabello XXL', 'precio' => 12, 'duracion' => '00:10:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'MECHA CABELLO CORTO BICOLOR', 'precio' => 30, 'duracion' => '00:30:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'MECHA CABELLO LARGO BICOLOR', 'precio' => 33, 'duracion' => '00:30:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'mechas bicolor cabello corto', 'precio' => 30, 'duracion' => '00:30:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'mechas bicolor cabello extra largo', 'precio' => 36, 'duracion' => '00:45:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'mechas bicolor cabello largo', 'precio' => 33, 'duracion' => '00:30:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'mechas bicolor cabello XXL', 'precio' => 39, 'duracion' => '00:45:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'mechas bicolor extra largo sin amoniaco', 'precio' => 38, 'duracion' => '00:59:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'mechas bicolor sin amoniaco cabello corto', 'precio' => 35, 'duracion' => '00:30:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'mechas bicolor sin amoniaco cabello largo', 'precio' => 37, 'duracion' => '00:30:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'mechas cabello corto', 'precio' => 17, 'duracion' => '00:30:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'MECHAS CABELLO CORTO SIN AMONIACO', 'precio' => 25, 'duracion' => '00:30:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'mechas cabello extra largo', 'precio' => 25, 'duracion' => '00:50:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'MECHAS CABELLO EXTRA LARGO SIN AMONIACO', 'precio' => 29, 'duracion' => '00:50:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'mechas cabello largo', 'precio' => 22, 'duracion' => '00:30:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'MECHAS CABELLO LARGO SIN AMONIACO', 'precio' => 27, 'duracion' => '00:30:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'mechas cabello XXL', 'precio' => 27, 'duracion' => '00:50:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'MECHAS CABELLO XXL SIN AMONIACO', 'precio' => 31, 'duracion' => '00:50:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'mechas cabellos XXL sin amoniaco', 'precio' => 40, 'duracion' => '00:59:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'MECHAS EMPLEADO con amoniaco (**precio por bol)', 'precio' => 10, 'duracion' => '00:30:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'MECHAS EMPLEADO sin amoniaco (precio por bol)', 'precio' => 12, 'duracion' => '00:12:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'MICROBLADING CEJAS', 'precio' => 250, 'duracion' => '02:00:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'microblading cejas', 'precio' => 250, 'duracion' => '01:00:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'Microblading con señal  pago previo 50', 'precio' => 200, 'duracion' => '01:30:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'MICROPIGMENTACION LABIOS', 'precio' => 180, 'duracion' => '02:00:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'micropigmentación labios', 'precio' => 180, 'duracion' => '01:00:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'MICROPIGMENTACION OJOS', 'precio' => 180, 'duracion' => '02:00:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'Nature frizz et nature', 'precio' => 6, 'duracion' => '00:10:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'Nature plex et nature', 'precio' => 8, 'duracion' => '00:10:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'PEDICURA SPA', 'precio' => 25, 'duracion' => '01:15:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'PEINAR cabello afro corto', 'precio' => 12, 'duracion' => '00:30:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'peinar cabello afro extra largo', 'precio' => 20, 'duracion' => '00:45:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'peinar cabello afro largo', 'precio' => 19, 'duracion' => '00:40:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'peinar cabello afro XXL', 'precio' => 22, 'duracion' => '00:45:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'peinar cabello corto normal', 'precio' => 6, 'duracion' => '00:15:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'peinar cabello corto rizo', 'precio' => 7, 'duracion' => '00:30:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'peinar cabello corto volumen', 'precio' => 8, 'duracion' => '00:25:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'peinar cabello extra largo normal', 'precio' => 12, 'duracion' => '00:30:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'peinar cabello extra largo rizo', 'precio' => 13, 'duracion' => '00:40:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'peinar cabello extra largo volumen', 'precio' => 13, 'duracion' => '00:30:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'peinar cabello largo normal', 'precio' => 9, 'duracion' => '00:25:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'peinar cabello largo rizo', 'precio' => 10, 'duracion' => '00:30:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'peinar cabello largo volumen', 'precio' => 11, 'duracion' => '00:30:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'peinar cabello XXL normal', 'precio' => 14, 'duracion' => '00:40:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'peinar cabello XXL rizo', 'precio' => 14, 'duracion' => '00:45:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'peinar cabello xxl volumen', 'precio' => 14, 'duracion' => '00:40:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'pienar cabello largo rizo', 'precio' => 10, 'duracion' => '00:35:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'PLEX EMPLEADO', 'precio' => 6, 'duracion' => '00:10:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'PROMOCION HIGIENE FACIAL', 'precio' => 20, 'duracion' => '00:30:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'RADIOFRECUENCIA 20 MINUTOS', 'precio' => 25, 'duracion' => '00:20:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'RADIOFRECUENCIA 30 MINUTOS', 'precio' => 30, 'duracion' => '00:30:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'recogido', 'precio' => 20, 'duracion' => '00:20:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'RELLENO EXTENSION PESTAÑAS', 'precio' => 35, 'duracion' => '00:30:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'Relleno pestañas', 'precio' => 25, 'duracion' => '00:20:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'RELLENO UÑAS GEL', 'precio' => 25, 'duracion' => '00:45:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'RETIRADA ESMALTE PERMANENTE', 'precio' => 4, 'duracion' => '00:15:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'RETIRADA ESMALTE TRADICIONAL', 'precio' => 2, 'duracion' => '00:00:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'RETIRADA UÑAS GEL', 'precio' => 8, 'duracion' => '00:15:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'RETOQUE MICROBLADING CEJAS', 'precio' => 150, 'duracion' => '01:00:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'Secado al aire', 'precio' => 4, 'duracion' => '00:10:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'semirecogido', 'precio' => 15, 'duracion' => '00:20:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'Señal microblading', 'precio' => 50, 'duracion' => '00:15:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'SESION MASCARA LED', 'precio' => 20, 'duracion' => '00:20:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'SESIÓN PRESOTERAPIA  30 MINUTOS', 'precio' => 9.9, 'duracion' => '00:30:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'SESIÓN PRESOTERAPIA 45 MINUTOS', 'precio' => 15.9, 'duracion' => '00:45:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'SUBIR EXTENSIONES', 'precio' => 65, 'duracion' => '00:30:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'SUPLEMENTO', 'precio' => 1, 'duracion' => '00:00:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'SUPLEMENTO ACELERADOR TINTE', 'precio' => 6, 'duracion' => '00:00:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'SUPLEMENTO MECHA', 'precio' => 10, 'duracion' => '00:00:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'SUPLEMENTO MECHA SIN AMONIACO', 'precio' => 12, 'duracion' => '00:00:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'SUPLEMENTO PLANCHA', 'precio' => 3, 'duracion' => '00:10:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'suplemento tinte PREMIUM', 'precio' => 4, 'duracion' => '00:00:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'suplemento tinte sin amoniaco PREMIUM', 'precio' => 7, 'duracion' => '00:10:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'tinte cabello corto PREMIUM', 'precio' => 9, 'duracion' => '00:10:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'tinte cabello corto SIN AMONIACO PREMIUM', 'precio' => 12, 'duracion' => '00:10:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'tinte cabello largo, extra largo, xxl  SIN AMONIACO PREMIUM', 'precio' => 13, 'duracion' => '00:10:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'tinte cabello largo, extra largo, xxl PREMIUM', 'precio' => 10, 'duracion' => '00:11:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'TINTE cejas', 'precio' => 3, 'duracion' => '00:10:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'TINTE EMPLEADO', 'precio' => 3, 'duracion' => '00:30:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'TRATAMIENTO ANTICAIDA EMPLEADO', 'precio' => 3, 'duracion' => '00:20:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'TRATAMIENTO AQUA VITAL', 'precio' => 45, 'duracion' => '00:40:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'TRATAMIENTO ARRUGAS OJOS Y FORTALECEDOR PESTAÑAS', 'precio' => 40, 'duracion' => '00:40:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'tratamiento bbglow+ lineaq gold o culture', 'precio' => 110, 'duracion' => '01:00:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'TRATAMIENTO CAIDA', 'precio' => 6, 'duracion' => '00:30:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'TRATAMIENTO CELULAR CONTROL AGE', 'precio' => 50, 'duracion' => '00:50:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'TRATAMIENTO CELULAS MADRES', 'precio' => 19, 'duracion' => '00:30:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'tratamiento culture', 'precio' => 80, 'duracion' => '00:30:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'TRATAMIENTO DESPIGMENTANTE LUMINOSITY', 'precio' => 50, 'duracion' => '00:50:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'Tratamiento keratin line et nature', 'precio' => 5, 'duracion' => '00:20:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'TRATAMIENTO KERATINA', 'precio' => 6, 'duracion' => '00:30:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'Tratamiento keratina pestañas', 'precio' => 40, 'duracion' => '01:30:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'tratamiento linea gold', 'precio' => 80, 'duracion' => '00:30:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'TRATAMIENTO PLEX', 'precio' => 12, 'duracion' => '00:10:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'Tratamiento puntas abiertas promocion', 'precio' => 25, 'duracion' => '01:00:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'Tratamiento puntas abiertas sin promo', 'precio' => 35, 'duracion' => '01:00:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'TRATAMIENTO PURIFICANTE EMPLEADO', 'precio' => 3, 'duracion' => '00:20:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'TRATAMIENTO PURIFICANTE Y ANTICASPA', 'precio' => 6, 'duracion' => '00:20:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'TRATAMIENTOO STEM C3', 'precio' => 50, 'duracion' => '00:50:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'TRENZAS', 'precio' => 7, 'duracion' => '00:30:00', 'id_categoria' => 1 ] );
        DB::table('servicios')->insert([ 'nombre' => 'UÑAS GEL', 'precio' => 35, 'duracion' => '01:00:00', 'id_categoria' => 2 ] );
        DB::table('servicios')->insert([ 'nombre' => 'UÑAS GEL EMPLEADO', 'precio' => 10, 'duracion' => '01:00:00', 'id_categoria' => 2 ] );


    }
}
